#
## Makefile for the HDMI output interface driver
#

ifeq ($(CONFIG_HDMI_OUTPUT_SUPPORT),y)
obj-y                                   += imap_HDMI.o
obj-y                                   += SIIAV_Config.o
obj-y                                   += SIIEDID.o
obj-y                                   += SIIHDCP.o
obj-y                                   += SIISiI9022A72.o
obj-y                                   += SIITPI_Access.o
obj-y                                   += SIITPI.o
obj-y                                   += SIIVideoModeTable.o
obj-y                                   += Globals.o
endif

